### ISSUE TITLE
Reset dynamic_template to proper default weights

### ISSUE THREAD

**Issue by MFatigati** [Sentinel-PaaS/sentinel-api#12]
Set default weights of template to 2 and 1 for production and canary for development, but these need to be changed back to 95 and 5 when development is complete, or at least when we have the ability to configure this on the fly.

```
http:
  services:
    {{ appName }}_weighted_svc:
      weighted:
        services:
          - name: {{ appName }}_production_svc@docker
            weight: {{ productionWeight|default(95) }}
          - name: {{ appName }}_canary_svc@docker
            weight: {{ canaryWeight|default(5) }}
```
