### ISSUE TITLE
Make "service" properties in compose templates more specific

### ISSUE THREAD

**Issue by MFatigati** [Sentinel-PaaS/sentinel-api#22]
In the templates, we need to amend the topmost service property to reflect the app name itself. Prometheus and Grafana seem to use these service names to organize their data, and if every service is identified in this way, things get flattened out in the monitoring data:

![Screen Shot 2022-03-25 at 7 53 04 PM](https://user-images.githubusercontent.com/28897430/160215637-58c44d47-5ece-4ae4-9dee-9b2b4d83ea72.png)

**Comment by MFatigati** [comment]
That is happening, despite the fact that multiple production/canary services are visible in my traefik. I've put stars above the lines that need amending:

```
---
version: "3.7"

services:
// ***************
  production:
    image: {{ productionImageName }}
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.http.routers.{{ appName }}_rtr.rule=Host(`{{ hostName }}`)
        - traefik.http.routers.{{ appName }}_rtr.entrypoints=web
        # - traefik.http.routers.app_router.tls.certresolver=le
        # the port listed here MUST be the internal post listed in the image
        - traefik.http.services.{{ appName }}_production_svc.loadbalancer.server.port={{ productionPort }}
        # Canary approach
        - traefik.http.routers.{{ appName }}_rtr.service={{ appName }}_weighted_svc@file
// ***************
  canary:
    image: {{ canaryImageName }}
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.{{ appName }}_canary_svc.loadbalancer.server.port={{ canaryPort }}
networks:
  traefik-public:
    driver: overlay
    attachable: true
    name: traefik-public
    external: true
```
