### ISSUE TITLE
Place node exporter on each newly created swarm node

### ISSUE THREAD

**Issue by MFatigati** [Sentinel-PaaS/sentinel-api#28]
Each time we create a new ec2 instance, it would be great to have some way to automatically install a new node exporter application associated with that node. That way we could get Prometheus metrics from the node itself. Right now node exporter is only available on the manager node, and `docker node inspect` does not give us any system level metrics (e.g., disk space available).

It would be nice to be able to provide, at least, disk space available, to help a user decide whether to scale instances up or down.

**Comment by MFatigati** [comment]
The `target` in `promtheus.yml` needs to correspond to the service name/port defined in the docker-compose file. e.g., if the compose file looks like this:

```
  node-exporter-manager-1:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - traefik-public
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
```
the config file should look like this:

```
  - job_name: 'node-exporter-manager-1'
    scrape_interval: 5s
    static_configs:
      - targets:
        - node-exporter-manager-1:9100
```
