### ISSUE TITLE
Incorporate auto-TLS for domains associated with each app

### ISSUE THREAD

**Issue by MFatigati** [Sentinel-PaaS/sentinel-api#30]
https://doc.traefik.io/traefik/https/acme/

**Comment by MFatigati** [comment]
Need to require an email address from the user for `certificatesResolvers` in the traefik static config

**Comment by MFatigati** [comment]
Essential to use `sudo chmod 600 acme.json` after transferring the file to the ec2 server. Previously, was getting the error `{"level":"error","msg":"The ACME resolver \"myresolver\" is skipped from the resolvers list because: unable to get ACME account: permissions 644 for /assets/letsencrypt/acme.json are too open, please use 600","time":"2022-03-26T19:25:31Z"}`

like this...
```
- name: Init Swarm Manager
  hosts: managers
  become: true
  gather_facts: False
  tasks:
    - name: Swarm Init
      command: docker swarm init --advertise-addr {{ hostvars[groups['managers'][0]].manager_private_ip }}
    - name: Copy assets directory to manager nodes
      copy:
        src: ../assets/
        dest: /
    - name: Restrict access to TLS cert document (transferred over in prior command)
      command: chmod 600 /letsencrypt/acme.json
// ...
```

**Comment by MFatigati** [comment]
Need to make sure `assets` folder containers `letsencrypt/acme.json`

The hosted domain needs to be pointing at the proper IP address prior to starting up traefik or deploying the new app, otherwise the tlschallenge will fail, and we would need to run `docker service update traefik_traefik` for the change to register.

**Comment by MFatigati** [comment]
dynamically rename the datasource to the SECURED version of the user's prometheus hostname in grafana's `datasource.yml`:

```
datasources:
  # <string, required> name of the datasource. Required
- name: Prometheus
  # <string, required> datasource type. Required
  type: prometheus
  # <string, required> access mode. direct or proxy. Required
  access: direct
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: https://prometheus-2.michaelfatigati.com
```

**Comment by MFatigati** [comment]
For testing, use a staging environment, but remove this line for production:

```
certificatesResolvers:
  myresolver:
    acme:
      email: fatigati.michael@gmail.com
      storage: /assets/letsencrypt/acme.json
      tlsChallenge: {}
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
```
