### ISSUE TITLE
Allow basic authentication for monitoring websites

### ISSUE THREAD

**Issue by MFatigati** [Sentinel-PaaS/sentinel-api#52]
Completed: Traefik uses bcrypt to allow a single password for the "admin" username on traefik, grafana and prometheus dashboard.

Seems to work, verify tomorrow:
- Grafana needs to skip TLS verification of prometheus, at least for now, and access prometheus as a server, not directly, so that it does not get caught up in the Traefik authentication:

```
- name: Prometheus
  # <string, required> datasource type. Required
  type: prometheus
  # <string, required> access mode. direct or proxy. Required
  access: proxy
// ...
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
     tlsSkipVerify: true
```

- Grafana needs to be run with the following environment variables in the docker compose, so avoid a double login page:
```
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - "GF_AUTH_ANONYMOUS_ORG_NAME=Main Org."
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
```
