### ISSUE TITLE
`cluster/initialize` command needs to run the template command on the stack-traefik-main file

### ISSUE THREAD

**Issue by MFatigati** [Sentinel-PaaS/sentinel-api#54]
e.g.,

```
    - name: Populate traefik-prometheus-grafana compose file and copy to manager
      template:
        src: ../assets/stack-traefik-main.yaml
        dest: /stack-traefik-main.yaml
```

Otherwise the routers look like this:

![Screen Shot 2022-04-01 at 7 19 13 AM](https://user-images.githubusercontent.com/28897430/161253538-3dc69695-5cdc-41fb-872c-a8a77b7b5a08.png)
