### ISSUE TITLE
Implement app.get(api/cluster)

### ISSUE THREAD

**Issue by samlipari** [Sentinel-PaaS/sentinel-api#6]
This endpoint should return the number of instances running and any other performance information we can obtain about the cluster

**Comment by MFatigati** [comment]
run node-exporter in global mode, and configure `prometheus.yml` to take into account node exporter's tasks, rather than just a single target:
```
  - job_name: 'node-exporter'
    scrape_interval: 5s
    # static_configs:
    #   - targets:
    #     - node-exporter:9100
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
```
